version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: nest_pg
    restart: always
    environment:
      POSTGRES_DB: tienda_bd
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
